language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

install: composer install
script:
  - mkdir -p build/logs
  - composer test
after_success:
  - travis_retry php vendor/bin/coveralls -v
